name: test
dsecription: Mixins and extensions
#version: 1.0.0
# honepage: https://example.com

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  equatable: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0