name: test
dsecription: A simple command-line application.
#version: 1.0.0
# honepage: https://example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dapendencies:
  equatable: ^2.0.0

dev_dependencies:
  test: ^1.11.0